config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users

  root 'home#index'

  resources :rides do 
    collection do
      post :search
    end
    member do
      post :join
    end
  end

  resources :cars do
  end

end

app/models/car.rb
class Car < ActiveRecord::Base
	belongs_to :user
	has_many :rides
	has_many :travellers
	validates_presence_of :seat, :car_type, :brand
	has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  	validates :seat, :numericality => { :greater_than_or_equal_to => 0 }
end

app/models/ride.rb
class Ride < ActiveRecord::Base
	belongs_to :owner, :class_name => 'User'
	has_one :car
	validates_presence_of :source, :destination, :arrival_time, :cost, :departure_time, :start_date

	def self.find_user_rides(current_user) 
		user_rides = current_user.rides
		user_rides << Ride.all.select {|ride| ride.travellers.include?(current_user.id)}
		user_rides
	end
end

app/models/traveller.rb
class Traveller < ActiveRecord::Base
	belongs_to :ride
	belongs_to :car
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cars
  has_many :rides
  validates_presence_of :first_name, :last_name, :location

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def full_name
  	self.first_name + " " + self.last_name
  end

  def is_owner? (ride)
    ride.user_id == self.id    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :location, :email, :password, :password_confirmation, :avatar) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :location, :email, :password, :password_confirmation, :current_password, :avatar) }
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = current_user.cars
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
    @car.user_id = current_user.id
    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params[:car].permit(:seat, :car_type, :brand, :user_id, :picture)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@ride = Ride.new
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :location, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :location, :password, :password_confirmation, :current_password, :avatar, :address, :age)
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :authenticate_user! , except: [:index, :show, :search]
  before_action :set_ride, only: [:show, :edit, :update, :destroy, :join]

  # GET /rides
  # GET /rides.json
  def index
    @rides = Ride.find_user_rides(current_user)
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
  end

  # GET /rides/new
  def new
    @ride = Ride.new
  end

  # GET /rides/1/edit
  def edit
  end

  # POST /rides
  # POST /rides.json
  def create
    @ride = current_user.rides.build(ride_params)
    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1
  # PATCH/PUT /rides/1.json
  def update
    unless current_user.is_owner?(@ride)
      flash[:error] = "You do not have the required permissions to perform this action"
      redirect_to root_path
    end
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    
    if current_user.is_owner?(@ride)
      @ride.destroy
      respond_to do |format|
        format.html { redirect_to rides_url, notice: 'Ride was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      flash[:error] = "You do not have the required permissions to perform this action"
    end
  end

  def search
    ride_param = params[:ride] if params[:ride].present?
    @rides = []
    if(ride_params[:source] != "")
      @rides = Ride.where(:source=>ride_params[:source])
    end
    if(ride_params[:destination] != "")
      @rides = Ride.where(:destination=>ride_params[:destination])
    end
    if (ride_params[:destination] != "" && ride_params[:source] != "")
      @rides = Ride.where(:source=>ride_params[:source]).where(:destination=>ride_params[:destination]).first
    end
    if (ride_params[:destination] == "" && ride_params[:source] == "")
      @rides = Ride.all
    end
    @rides.select {|ride| ride.seats > (ride.travellers.count + 1)}
  end

  def join
    @ride.travellers << current_user.id
    if @ride.save
      flash[:notice] = "Congratulations you have been added to ride"
      redirect_to ride_path(@ride)
    else
      flash[:error] = "Sorry could not be added to ride."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ride_params
      params[:ride].permit(:source,:destination,:cost,:departure_time,:arrival_time,:route,:travellers,:user_id, :start_date, :seats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/cars/_form.html.erb
<%= form_for @car, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <%= image_tag @car.picture.url(:medium), size: "350x300" %>
  <div class="form-group">
    <%= f.label :picture %><br />
    <%= f.file_field :picture, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :seat %><br />
    <%= f.text_field :seat , class: "form-control" %>
  </div>
    <%= error_span(@car[:seat]) %>
  <div class="form-group">
    <%= f.label :car_type %><br />
    <%= f.text_field :car_type, class: "form-control" %>
  </div>
    <%= error_span(@car[:car_type]) %>
  <div class="form-group">
    <%= f.label :brand %><br />
    <%= f.text_field :brand, class: "form-control" %>
  </div>
    <%= error_span(@car[:brand]) %>
  <div class="form-group">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cars_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<%- model_class = Car -%>

<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h2>
      </div>
      <div class="panel-body" style="margin: 0 40px">
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:picture) %></th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:seat) %></th>
      <th><%= model_class.human_attribute_name(:car_type) %></th>
      <th><%= model_class.human_attribute_name(:brand) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= image_tag car.picture, size: "100x100" %></td>
        <td><%= link_to car.id, car_path(car) %></td>
        <td><%= car.seat %></td>
        <td><%= car.car_type %></td>
        <td><%= car.brand %></td>
        <td><%= car.user_id %></td>
        <td><%=l car.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_car_path(car), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      car_path(car),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_car_path,
            :class => 'btn btn-primary' %>

app/views/cars/new.html.erb
<%- model_class = Car -%>

<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h2>
      </div>
      <div class="panel-body" style="margin: 0 40px">
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:picture) %>:</strong></dt>
  <dd><%= image_tag @car.picture, size: "100x100" %></dd>
  <dt><strong><%= model_class.human_attribute_name(:seat) %>:</strong></dt>
  <dd><%= @car.seat %></dd>
  <dt><strong><%= model_class.human_attribute_name(:car_type) %>:</strong></dt>
  <dd><%= @car.car_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:brand) %>:</strong></dt>
  <dd><%= @car.brand %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @car.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              cars_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_car_path(@car), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              car_path(@car),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/home/index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="row">
			<h2>Welcome to the Hackathon ride</h2>
		</div>
		<div class="row">
			<div class="col-md-10">
				<div class="row">
				  <div class="col-md-12">
				   Search For your rides Available<br\>
					<%= form_for @ride, :url => {:controller => "rides", :action => "search" }, :html => { :class => 'form-inline' } do |f| %>
					  <div class="form-group">
					  	<%= f.label "From" %>
    				    <%= f.text_field :source, class: "form-control" %>
					  </div>
					  <div class="form-group">
					  	<%= f.label "To" %>
					  	<%= f.text_field :destination, class: "form-control"%>
					  </div>
					  <%= f.button "Search", :class => ' btn btn-primary' %>
					<% end %>
					<br>
				  </div>
				</div>
			    <div>
				  <%= link_to "Display All Rides", rides_path, class: 'btn btn-primary btn-lg' %>
			    </div>
			</div>
			<div class="col-md-2">
				<div class="row">
					<h3>Travelling alone?</h3>
					<br>
					<div>
						<%= link_to "Offer a Ride", new_ride_path, class: 'btn btn-primary btn-lg' %>
					</div>
				</div>
			</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackathon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to(image_tag("hackathon.jpg", size: "200x35", alt: "Hackathon"), root_path) %>
      </div>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= image_tag current_user.avatar.url(:thumb), size: "50x40" %>
          </li>
          <li>
            <%= link_to current_user.full_name, edit_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-info fade alert-dismissable in">
        <a class="close" data-dismiss="alert" href="#">&times;</a>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/rides/_form.html.erb
<%= form_for @ride, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :source %><br />
    <%= f.text_field :source, class: "form-control", :onblur => 'DrawMap()' %>
  </div>
  <%= error_span(@ride[:source]) %>
  <div class="form-group">
    <%= f.label :destination %><br />
    <%= f.text_field :destination, class: "form-control", :onblur => 'DrawMap()' %>
  </div>
  <%= error_span(@ride[:destination]) %>
  <div class="form-group">
    <%= f.label :cost %><br />
    <%= f.text_field :cost, class: "form-control" %>
  </div>
  <%= error_span(@ride[:cost]) %>
  <div class="form-group">
    <%= f.label :arrival_time %><br />
    <%= f.time_field :arrival_time, class: "form-control" %>
  </div>
  <%= error_span(@ride[:duration]) %>
  <div class="form-group">
    <%= f.label :departure_time %><br />
    <%= f.time_field :departure_time, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :start_date %><br />
    <%= f.date_field :start_date, class: "form-control" %>
  </div>
  <%= error_span(@ride[:route]) %>
  <div class="form-group">
    <%= f.label :route %><br />
    <%= f.text_field :route, class: "form-control", :onblur => 'DrawMap()' %>
  </div>
  <div class="form-group">
    <%= f.label :travellers %><br />
    <%= f.text_field :travellers, class: "form-control"%>
  </div>
  <%= error_span(@ride[:travellers]) %>
  <div class="form-group">
    <%= f.label :seats %><br />
    <%= f.number_field :seats, class: "form-control"%>
  </div>
  <%= error_span(@ride[:travellers]) %>
  <div class="form-group">
    <%= f.button :submit, :class => ' btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  rides_path, :class => 'btn btn-default' %>
  </div>
  <div style='width: 800px;'>
    <div id="map" style='width: 400px; height: 400px;'></div>
  </div>
<% end %>

<script>
$(window).load(function() {

  window.markersArray = [];
  window.latlon = [];
  window.flightPath = '';
  loadScript();
});

var map;

function initialize() {

  

function clearOverlays() {
  for (var i = 0; i < markersArray.length; i++ ) {
    markersArray[i].setMap(null);
  }
  markersArray.length = 0;
}
  
  
  

  var mapOptions = {
          center: new google.maps.LatLng(13.0827, 80.2707),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.RoadMap,
          panControl: true,
          scaleControl: false,
          streetViewControl: true,
          overviewMapControl: true
        };
        // initializing map
        map = new google.maps.Map(document.getElementById("map"),mapOptions);
        
   // geocoding 
      var geocoding  = new google.maps.Geocoder();
      $("#submit_button_geocoding").click(function(){

      var address = $("#search_box_geocoding").val();
        codeAddress(geocoding,address,false);

      });
      
      latlon = [
        {lat: 13.1827, lng: 80.4707},
      ];
      console.log(latlon);
      var flightPath = new google.maps.Polyline({
        path: latlon,
        geodesic: true,
        strokeColor: '#FF0000',
        strokeOpacity: 1.0,
        strokeWeight: 2
      });

      flightPath.setMap(map);

   
}

var info;

function codeAddress(geocoding,address,flag){
  var addLatLon = '';
  if(address.length > 0){
    geocoding.geocode({'address': address},function(results, status){
      if(status == google.maps.GeocoderStatus.OK){
        map.setCenter(results[0].geometry.location);
        var addLatLon = {
         lat : results[0].geometry.location.lat(),
         lng : results[0].geometry.location.lng()
        }
        latlon.push(addLatLon);
        var marker  =  new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
        });
        markersArray.push(marker);
        google.maps.event.addListener(marker,"click",function(){});
        }else{
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }else{
    console.log("Search field can't be blank");
  }

}

function loadScript() {
  console.log("map loading ...");
  var script = document.createElement('script');
  script.type = 'text/javascript';
  //'https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyBJYFdplGeKUUEmGZ-vL4ydiSZ09Khsa_o&sensor=false&libraries=drawing'
  script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp' +
    //'&v=3.14'+
    //'&key=AIzaSyBJYFdplGeKUUEmGZ-vL4ydiSZ09Khsa_o'+
    '&libraries=drawing'+
    '&callback=initialize';
  document.body.appendChild(script);
}
function DrawMap() {

  latlon = [
        {lat: 13.1827, lng: 80.4707},
      ];

  for (var i = 0; i < markersArray.length; i++ ) {
    markersArray[i].setMap(null);
  }
  markersArray.length = 0;
  var geocoding  = new google.maps.Geocoder();
  var source =  codeAddress(geocoding,$('#ride_source').val(),true);
  var midway = $('#ride_route').val();
  midway = midway.replace("{",'').replace("}",'').split(",");

  for (i = 0; i < midway.length; i++) { 
      console.log(midway[i]);
      codeAddress(geocoding,midway[i],true);
  }
  setTimeout(function() { var des = codeAddress(geocoding,$('#ride_destination').val(),true); }, 1000);

  if(flightPath){
    flightPath.setMap(null);
  }
  setTimeout(function() { drawing(); }, 3000);

}
function drawing() {
  latlon.shift();
  console.log(latlon);
      flightPath = new google.maps.Polyline({
        path: latlon,
        geodesic: true,
        strokeColor: '#FF0000',
        strokeOpacity: 1.0,
        strokeWeight: 2
      });

      flightPath.setMap(map);
}
</script>

app/views/rides/edit.html.erb
<%- model_class = Ride -%>
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h2>
      </div>
      <div class="panel-body" style="margin: 0 40px">
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/rides/index.html.erb
<%- model_class = Ride -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<% if @rides.present? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:source) %></th>
        <th><%= model_class.human_attribute_name(:destination) %></th>
        <th><%= model_class.human_attribute_name(:cost) %></th>
        <th><%= model_class.human_attribute_name(:start_date) %></th>
        <th><%= model_class.human_attribute_name(:arrival_time) %></th>
        <th><%= model_class.human_attribute_name(:departure_time) %></th>
        <th><%= model_class.human_attribute_name(:route) %></th>
        <th><%= model_class.human_attribute_name(:travellers) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @rides.each do |ride| %>
        <tr>
          <td><%= ride.source %></td>
          <td><%= ride.destination %></td>
          <td><%= ride.cost %></td>
          <td><%= ride.start_date %></td>
          <td><%= ride.arrival_time %></td>
          <td><%= ride.departure_time %></td>
          <td><%= ride.route %></td>
          <td><%= ride.travellers %></td>
          <td><%=l ride.created_at %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_ride_path(ride), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        ride_path(ride),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2> Sorry Could not find any rides with the search criterion </h2>
<% end %>

<%= link_to t('Add new Ride', :default => t("helpers.links.new")),
            new_ride_path,
            :class => 'btn btn-primary' %>

app/views/rides/new.html.erb
<%- model_class = Ride -%>

<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h2>
      </div>
      <div class="panel-body" style="margin:0 40px">
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/rides/search.html.erb
<%- model_class = Ride -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<% if @rides.present? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:source) %></th>
        <th><%= model_class.human_attribute_name(:destination) %></th>
        <th><%= model_class.human_attribute_name(:cost) %></th>
        <th><%= model_class.human_attribute_name(:start_date) %></th>
        <th><%= model_class.human_attribute_name(:arrival_time) %></th>
        <th><%= model_class.human_attribute_name(:departure_time) %></th>
        <th><%= model_class.human_attribute_name(:route) %></th>
        <th><%= model_class.human_attribute_name(:travellers) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @rides.each do |ride| %>
        <tr>
          <td><%= ride.source %></td>
          <td><%= ride.destination %></td>
          <td><%= ride.cost %></td>
          <td><%= ride.start_date %></td>
          <td><%= ride.arrival_time %></td>
          <td><%= ride.departure_time %></td>
          <td><%= ride.route %></td>
          <td><%= ride.travellers %></td>
          <td><%=l ride.created_at %></td>
          <td>
            <% if (current_user && current_user.is_owner?(ride)) %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_ride_path(ride), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        ride_path(ride),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
            <% else %>
              <%= form_tag(join_ride_path(ride), :html => { :class => 'form-horizontal' }, method: :post) do %>
                 <%= submit_tag("Join Ride") %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2> Sorry Could not find any rides with the search criterion </h2>
<% end %>